export const mockSpaces = [
  {
    id: 1,
    name: "Lab 101",
    type: "Computer Lab",
    capacity: 40,
    equipment: ["PCs", "Projector", "Whiteboard"],
  },
  {
    id: 2,
    name: "Seminar Hall 2",
    type: "Seminar Hall",
    capacity: 120,
    equipment: ["Projector", "PA System", "Stage Lighting"],
  },
  {
    id: 3,
    name: "Classroom C1",
    type: "Classroom",
    capacity: 60,
    equipment: ["Whiteboard", "Smart Screen"],
  },
  {
    id: 4,
    name: "Innovation Studio",
    type: "Workshop Lab",
    capacity: 30,
    equipment: ["3D Printer", "Laser Cutter", "Workbenches"],
  },
];

export const mockBookings = [
  {
    id: 101,
    title: "AI Lab Session",
    type: "Lab",
    spaceId: 1,
    date: "2026-02-14",
    start: "09:00",
    end: "11:00",
    participants: 35,
    equipment: ["PCs"],
    status: "Approved",
    requestedBy: "Dr. Singh",
    requestedRole: "faculty",
  },
  {
    id: 102,
    title: "Robotics Club Meetup",
    type: "Club",
    spaceId: 4,
    date: "2026-02-14",
    start: "14:00",
    end: "16:00",
    participants: 24,
    equipment: ["Workbenches"],
    status: "Pending",
    requestedBy: "Asha Patel",
    requestedRole: "coordinator",
  },
  {
    id: 103,
    title: "Faculty Seminar",
    type: "Seminar",
    spaceId: 2,
    date: "2026-02-15",
    start: "10:00",
    end: "12:00",
    participants: 90,
    equipment: ["Projector", "PA System"],
    status: "Pending",
    requestedBy: "Prof. Lee",
    requestedRole: "faculty",
  },
];

export const mockTimetable = [
  {
    id: 201,
    spaceId: 1,
    day: "Mon",
    start: "09:00",
    end: "12:00",
    title: "CSE 301 - Data Structures",
  },
  {
    id: 202,
    spaceId: 2,
    day: "Tue",
    start: "11:00",
    end: "13:00",
    title: "MBA 210 - Marketing",
  },
  {
    id: 203,
    spaceId: 3,
    day: "Wed",
    start: "10:00",
    end: "12:00",
    title: "PHY 102 - Optics",
  },
  {
    id: 204,
    spaceId: 4,
    day: "Thu",
    start: "13:00",
    end: "15:00",
    title: "ENG 412 - Product Design",
  },
];
