export const mockSpaces = [
  {
    id: 1,
    name: "Bytes Lab",
    type: "Computer Lab",
    capacity: 120,
  },
  {
    id: 2,
    name: "Vista Hall",
    type: "Seminar Hall",
    capacity: 200,
  },
  {
    id: 3,
    name: "Classroom SF05",
    type: "Classroom",
    capacity: 80,
  },
  {
    id: 4,
    name: "Code Studio",
    type: "Computer Lab",
    capacity: 250,
  },
];

export const mockBookings = [
  {
    id: 101,
    title: "AI Lab Session",
    type: "Lab",
    spaceId: 1,
    date: "2026-02-14",
    start: "09:00",
    end: "11:00",
    participants: 35,
    status: "Approved",
    requestedBy: "Dr. Ram Charan",
    requestedRole: "faculty",
  },
  {
    id: 102,
    title: "Robotics Club Meetup",
    type: "Club",
    spaceId: 4,
    date: "2026-02-14",
    start: "14:00",
    end: "16:00",
    participants: 24,
    status: "Pending",
    requestedBy: "Mr. Kumar",
    requestedRole: "coordinator",
  },
  {
    id: 103,
    title: "Faculty Seminar",
    type: "Seminar",
    spaceId: 2,
    date: "2026-02-15",
    start: "10:00",
    end: "12:00",
    participants: 90,
    status: "Pending",
    requestedBy: "Prof. Rani",
    requestedRole: "faculty",
  },
];

export const mockTimetable = [
  {
    id: 201,
    spaceId: 1,
    day: "Mon",
    start: "09:00",
    end: "12:00",
    title: "CSE 301 - Data Structures",
  },
  {
    id: 202,
    spaceId: 2,
    day: "Tue",
    start: "11:00",
    end: "13:00",
    title: "MBA 210 - Marketing",
  },
  {
    id: 203,
    spaceId: 3,
    day: "Wed",
    start: "10:00",
    end: "12:00",
    title: "PHY 102 - Optics",
  },
  {
    id: 204,
    spaceId: 4,
    day: "Thu",
    start: "13:00",
    end: "15:00",
    title: "ENG 412 - Product Design",
  },
];
